// src/lib/constants.ts
export const COMPANY = {
  name: 'CVEEEZ',
  nameAr: 'سي ڤييز',
  slogan: 'نحن نحقق أهدافك',
  sloganEn: 'We achieve your goals',
  description:
    'شركة متخصصة في خدمات كتابة السيرة الذاتية والتوظيف بالذكاء الاصطناعي',
  location: 'Cairo, Egypt',
  email: 'cveeez@cveeez.online',
  phones: [
    { number: '+201065236963', label: 'الخط الأول' },
    { number: '+201550363738', label: 'الخط الثاني' },
  ],
  supportPhone: { number: '0934678331', hours: 'من 10 صباحاً إلى 4 مساءً' },
  socials: {
    website: 'https://cveeez.net/',
    facebook: 'https://www.facebook.com/cveeez.eg',
    linkedin: 'https://www.linkedin.com/company/cveez/',
    instagram: 'https://www.instagram.com/cveeez0',
  },
  brandColor: '#22c55e',
  stats: {
    cvsCreated: '+10,000',
    happyUsers: '+10,000',
    templates: 21,
    satisfaction: '95%',
  },
} as const;

export const QR_LINKS = [
  { url: COMPANY.socials.website, label: 'الموقع الرسمي', icon: '🌐' },
  { url: COMPANY.socials.facebook, label: 'فيسبوك', icon: '📘' },
  { url: COMPANY.socials.linkedin, label: 'لينكدإن', icon: '💼' },
  { url: COMPANY.socials.instagram, label: 'إنستجرام', icon: '📸' },
  {
    url: `tel:${COMPANY.phones[0].number}`,
    label: COMPANY.phones[0].label,
    icon: '📞',
  },
  {
    url: `tel:${COMPANY.phones[1].number}`,
    label: COMPANY.phones[1].label,
    icon: '📱',
  },
  { url: `mailto:${COMPANY.email}`, label: 'البريد الإلكتروني', icon: '📧' },
] as const;

export const JOBS = [
  {
    id: 'moderator',
    title: 'مودريتور',
    titleEn: 'Moderator',
    icon: '🛡️',
    description: 'إدارة المحتوى والمجتمعات الرقمية',
    color: 'from-blue-500/20 to-blue-600/20',
  },
  {
    id: 'cv-designer',
    title: 'مصممي سيرة ذاتية',
    titleEn: 'CV Designer',
    icon: '📄',
    description: 'تصميم سير ذاتية احترافية',
    color: 'from-emerald-500/20 to-emerald-600/20',
  },
  {
    id: 'graphic-designer',
    title: 'مصمم عام',
    titleEn: 'Graphic Designer',
    icon: '🎨',
    description: 'تصميم جرافيك وبصريات إبداعية',
    color: 'from-purple-500/20 to-purple-600/20',
  },
  {
    id: 'tailor',
    title: 'خياطين',
    titleEn: 'Tailor',
    icon: '🧵',
    description: 'أعمال الخياطة والتفصيل',
    color: 'from-rose-500/20 to-rose-600/20',
  },
  {
    id: 'fabric-cutter',
    title: 'مقص دار',
    titleEn: 'Fabric Cutter',
    icon: '✂️',
    description: 'قص الأقمشة والباترونات',
    color: 'from-orange-500/20 to-orange-600/20',
  },
  {
    id: 'affiliate-marketer',
    title: 'مسوقين بالعمولة',
    titleEn: 'Affiliate Marketer',
    icon: '📢',
    description: 'تسويق بالعمولة وجلب عملاء',
    color: 'from-yellow-500/20 to-yellow-600/20',
  },
  {
    id: 'developer',
    title: 'مبرمجين',
    titleEn: 'Developer',
    icon: '💻',
    description: 'تطوير وبرمجة المواقع والتطبيقات',
    color: 'from-cyan-500/20 to-cyan-600/20',
  },
  {
    id: 'content-writer',
    title: 'كاتب محتوى',
    titleEn: 'Content Writer',
    icon: '✍️',
    description: 'كتابة محتوى إبداعي وتسويقي',
    color: 'from-indigo-500/20 to-indigo-600/20',
  },
  {
    id: 'ugc-creator',
    title: 'UGC',
    titleEn: 'UGC Creator',
    icon: '📱',
    description: 'صناعة محتوى المستخدمين',
    color: 'from-pink-500/20 to-pink-600/20',
  },
  {
    id: 'programming-intern',
    title: 'متدربين برمجة',
    titleEn: 'Programming Intern',
    icon: '🎓',
    description: 'تدريب وتعلم البرمجة',
    color: 'from-teal-500/20 to-teal-600/20',
  },
  {
    id: 'cleaning-worker',
    title: 'عاملة نظافة',
    titleEn: 'Cleaning Worker',
    icon: '🧹',
    description: 'خدمات النظافة والترتيب',
    color: 'from-lime-500/20 to-lime-600/20',
  },
] as const;

export type JobSlug = (typeof JOBS)[number]['id'];

// Job-specific questions
export const JOB_QUESTIONS: Record<
  string,
  Array<{
    id: string;
    text: string;
    type: 'text' | 'textarea' | 'select' | 'number' | 'url' | 'file' | 'radio';
    required: boolean;
    placeholder?: string;
    options?: string[];
  }>
> = {
  // ملاحظة: التقييم الآلي (الأوزان/الدرجة) لكل سؤال موجود في src/lib/scoring.ts
  // مربوط بالـ id بتاع كل سؤال — لو غيّرت id هنا غيّره هناك كمان.
  moderator: [
    {
      id: 'education_level',
      text: 'إيه أعلى مؤهل دراسي وصلت له؟ (للعلم ده بيانات بس، مش بيأثر على تقييمك)',
      type: 'select',
      required: false,
      options: ['ثانوي/دبلوم', 'معهد/دبلومة فوق المتوسط', 'بكالوريوس/ليسانس', 'دراسات عليا'],
    },
    {
      id: 'specialization',
      text: 'تخصصك الدراسي إيه؟ (اختياري)',
      type: 'text',
      required: false,
      placeholder: 'مثال: إدارة أعمال / تسويق / لغات / أي تخصص',
    },
    // ===== بيانات شخصية إضافية (بيانات فقط — مش بتأثر على الدرجة) =====
    {
      id: 'whatsapp_number',
      text: 'رقم الواتساب بتاعك (مهم للتواصل السريع في شغل الشات)',
      type: 'text',
      required: false,
      placeholder: 'مثال: 01012345678',
    },
    {
      id: 'alt_phone',
      text: 'رقم تاني للتواصل (احتياطي)',
      type: 'text',
      required: false,
      placeholder: 'مثال: 01112223334',
    },
    {
      id: 'age',
      text: 'سنك كام؟',
      type: 'number',
      required: false,
      placeholder: 'مثال: 25',
    },
    {
      id: 'gender',
      text: 'النوع',
      type: 'select',
      required: false,
      options: ['ذكر', 'أنثى'],
    },
    {
      id: 'marital_status',
      text: 'الحالة الاجتماعية',
      type: 'select',
      required: false,
      options: ['أعزب/عزباء', 'متزوج/متزوجة', 'أخرى'],
    },
    {
      id: 'military_status',
      text: 'الموقف من التجنيد (للذكور)',
      type: 'select',
      required: false,
      options: ['أديت الخدمة', 'مؤجل', 'معاف نهائي', 'لا ينطبق (أنثى)'],
    },
    {
      id: 'employment_status',
      text: 'وضعك المهني حالياً؟',
      type: 'select',
      required: false,
      options: [
        'متفرغ تماماً',
        'بشتغل حالياً وبدور على أحسن',
        'بشتغل بدوام جزئي',
        'طالب',
        'مش بشتغل دلوقتي',
      ],
    },
    {
      id: 'referral_source',
      text: 'عرفت عن الوظيفة دي منين؟',
      type: 'select',
      required: false,
      options: ['فيسبوك', 'إنستجرام', 'لينكدإن', 'صديق/معرفة', 'إعلان', 'جوجل/بحث', 'غير كده'],
    },
    {
      id: 'sales_experience_years',
      text: 'عندك كام سنة خبرة فعلية في خدمة العملاء أو المبيعات أو الرد على العملاء بالشات؟',
      type: 'select',
      required: false,
      options: ['من غير خبرة', 'أقل من سنة', '1-2 سنة', '3-5 سنين', 'أكتر من 5 سنين'],
    },
    {
      id: 'experience_summary',
      text: 'احكيلنا باختصار عن خبرتك في خدمة العملاء أو الشات أو المبيعات: شغلت إيه بالظبط، وإيه أهم النتايج اللي حققتها؟',
      type: 'textarea',
      required: false,
      placeholder: 'مثال: اشتغلت سيلز شات لشركة كذا سنتين، كنت بقفل في المتوسط كذا عميل في الشهر وكنت أعلى واحد في الفريق...',
    },
    {
      id: 'companies_worked',
      text: 'اكتب أسماء الشركات اللي اشتغلت فيها، ودورك في كل واحدة، ومدة شغلك فيها. (بنتأكد منها في الانترفيو)',
      type: 'text',
      required: false,
      placeholder: 'مثال: شركة X – سيلز شات – سنة ونص | شركة Y – خدمة عملاء – 8 شهور',
    },
    {
      id: 'daily_closes',
      text: 'في المتوسط كنت بتقفل كام عميل/صفقة في اليوم على الشات في آخر شغل ليك؟ (الرقم ده أقرب لطبيعة شغلنا من رقم مبيعات إجمالي)',
      type: 'select',
      required: false,
      options: ['لسه مقفلتش مبيعات قبل كده', '1-2 في اليوم', '3-5 في اليوم', '6-10 في اليوم', 'أكتر من 10 في اليوم'],
    },
    {
      id: 'biggest_sales_story',
      text: 'احكيلنا عن أكبر نتيجة مبيعات حققتها فعلاً: وصلت لها إزاي، كانت ثابتة كل شهر ولا مرة واحدة، وكام % من التارجت؟ (الأرقام بنراجعها بشري وبنتأكد منها في الانترفيو)',
      type: 'textarea',
      required: false,
      placeholder: 'مثال: كنت بحقق 120% من التارجت بشكل ثابت كل شهر عن طريق المتابعة والتعامل مع الاعتراضات...',
    },
    {
      id: 'persuasion_writing_sample',
      text: 'أهم سؤال (بنراجعه بشري): عميل متردد ومش متأكد إنه يشتري خدمة كتابة السيرة الذاتية. اكتب بالظبط الرسالة اللي هتبعتها له على الشات عشان تقنعه يكمّل ويشتري. خليها طبيعية ومركّزة زي شات حقيقي.',
      type: 'textarea',
      required: false,
      placeholder: 'اكتب الرسالة الفعلية اللي هتبعتها للعميل...',
    },
    {
      id: 'objection_handling',
      text: 'عميل قالك على الشات: "السعر غالي عليّا" أو "هفكّر وأرجعلك". اكتب بالظبط هترد عليه إزاي عشان تقنعه يكمّل.',
      type: 'textarea',
      required: false,
      placeholder: 'اكتب ردك الفعلي على الاعتراض...',
    },
    {
      id: 'save_the_sale',
      text: 'عميل دفع خلاص واستلم نسخة السيرة الذاتية بس مش عاجبه ورجع زعلان على الشات. هتتصرف إزاي عشان ترضّيه وتحافظ عليه كعميل؟',
      type: 'textarea',
      required: false,
      placeholder: 'اكتب ردك خطوة بخطوة...',
    },
    {
      id: 'speed_triage',
      text: 'لو وصلك 5 عملاء في نفس الوقت على الشات، بتتصرف إزاي؟',
      type: 'radio',
      required: false,
      options: [
        'برد على الأقرب للشراء/الأكثر جدية الأول وأطمّن الباقي إني جاي عليهم',
        'برد بالترتيب اللي وصلوا بيه واحد ورا التاني',
        'بنسخ نفس الرد وأبعته للكل',
        'بيحصلي ضغط وبتلخبط',
      ],
    },
    {
      id: 'ai_tools_used',
      text: 'أنهي أدوات ذكاء اصطناعي استخدمتها فعلاً في شغل حقيقي قبل كده؟',
      type: 'select',
      required: false,
      options: [
        'مستخدمتش أدوات AI في الشغل قبل كده',
        'استخدمت أداة واحدة بشكل بسيط',
        'بستخدم ChatGPT/Claude/Gemini في شغلي بشكل منتظم',
        'بستخدم أكتر من أداة AI وعندي طريقة شغل ثابتة بيهم',
      ],
    },
    {
      id: 'ai_prompt_sample',
      text: 'اكتب البرومبت (الأمر) الفعلي اللي ممكن تكتبه لأداة AI عشان تساعدك ترد على عميل متردد أو تصيغ رد إقناعي سريع.',
      type: 'textarea',
      required: false,
      placeholder: 'اكتب البرومبت بالظبط زي ما هتكتبه للأداة...',
    },
    {
      id: 'has_laptop',
      text: 'معاك لاب توب خاص بيك تقدر تشتغل عليه فوراً؟ ومعاك نت ثابت ومكان هادي للشغل؟',
      type: 'radio',
      required: false,
      options: [
        'آه، لاب توب خاص + نت ثابت + مكان هادي',
        'معايا لاب توب بس النت/المكان مش مظبوط',
        'لسه هحتاج أوفّر لاب توب',
        'لأ',
      ],
    },
    {
      id: 'available_shifts',
      text: 'الشغل مقسوم على 3 شيفتات (اليوم تقريباً 3 شيفتات كل واحد حوالي 8 ساعات؛ الصباحي بيبدأ 8 صباحاً). أنهي شيفت/شيفتات تقدر تلتزم بيها بثبات؟ (لو أكتر من شيفت اكتبهم مفصولين بفاصلة)',
      type: 'text',
      required: false,
      placeholder: 'مثال: ليلي | أو: صباحي، مسائي | أو: أي شيفت',
    },
    {
      id: 'training_commitment',
      text: 'قبل الشغل الفعلي في فترة تدريب من أسبوع لشهر حسب سرعة استيعابك. مستعد تلتزم بيها؟',
      type: 'radio',
      required: false,
      options: ['آه تماماً ومستعد أتعلم بأقصى سرعة', 'مستعد بس محتاج أفهم تفاصيل أكتر', 'مش مناسب ليا'],
    },
    {
      id: 'contract_commitment',
      text: 'الوظيفة عقد سنة وفيه شرط جزائي بيتفعّل لو الموظف مشي من غير ما يبلّغ بشهر على الأقل. التفاصيل الكاملة (المبلغ والشروط) بتتشرح وبتتوقّع في مرحلة التعاقد نفسها. مبدئياً مستعد للالتزام بمدة سنة؟',
      type: 'radio',
      required: false,
      options: [
        'آه مبدئياً مستعد ألتزم بالسنة والإبلاغ المسبق',
        'مبدئياً موافق بس محتاج أراجع تفاصيل العقد قبل التوقيع',
        'مش متأكد',
      ],
    },
    {
      id: 'conduct_acknowledgement',
      text: 'الوظيفة بتتطلب الالتزام بآداب ومهنية العمل، وفي حالة الإخلال الجسيم بالعقد يحق للشركة اتخاذ الإجراءات القانونية وفق بنود العقد المتفق عليها. هتطّلع على التفاصيل الكاملة قبل التوقيع. تقدر تأكد إنك مطّلع على الكلام ده ومبدئياً موافق؟',
      type: 'radio',
      required: false,
      options: ['آه مطّلع ومبدئياً موافق وملتزم بالمهنية', 'مطّلع وحابب أراجع التفاصيل في الانترفيو', 'لأ'],
    },
    {
      id: 'reports_commitment',
      text: 'المدير بيبعت ملفات وتقارير لازم تتقري وتتنفّذ بدقة. احكي موقف قبل كده اتطلب منك تتعلم تعليمات/أداة جديدة بسرعة وتلتزم بيها، وإيه اللي عملته؟',
      type: 'textarea',
      required: false,
      placeholder: 'مثال: في شغلي السابق وصلني مانيوال جديد للردود، قريته وطبقته في يومين وكنت بسأل وقت اللزوم...',
    },
    {
      id: 'won_back_customer',
      text: 'احكي عن آخر عميل رفض في الأول وانت قدرت ترجّعه يشتري. عملت إيه بالظبط؟ (لو مفيش، اكتب "لسه مجرّبتش")',
      type: 'textarea',
      required: false,
      placeholder: 'اكتب الموقف الفعلي وإزاي قلبت الرفض لقبول...',
    },
    {
      id: 'governorate',
      text: 'محافظة سكنك إيه؟ (بيانات بس — الشغل أونلاين فالمكان مش بيأثر على تقييمك)',
      type: 'text',
      required: false,
      placeholder: 'مثال: القاهرة / أسيوط / الإسكندرية / المنصورة...',
    },
    {
      id: 'start_availability',
      text: 'أقرب وقت تقدر تبدأ فيه الشغل (بعد التدريب)؟',
      type: 'select',
      required: false,
      options: ['فوراً', 'خلال أسبوع', 'خلال أسبوعين', 'أكتر من أسبوعين'],
    },
    {
      id: 'expected_salary',
      text: 'توقعك للمرتب الشهري كام بالجنيه المصري؟ (للعلم المرتب بيتناقش ويتحدد في الانترفيو — ده مجرد توقع مبدئي للبيانات ومش بيأثر على تقييمك)',
      type: 'number',
      required: false,
      placeholder: 'مثال: 8000',
    },
    {
      id: 'portfolio_or_profile',
      text: 'لو عندك بروفايل أو بورتفوليو أو حساب بيوضّح شغلك (لينكدإن مثلاً)، حُط اللينك هنا.',
      type: 'url',
      required: false,
      placeholder: 'https://...',
    },
    {
      id: 'seriousness_pitch',
      text: 'ليه نختارك أنت بالذات للدور ده، وإيه اللي بيضمنلنا جديتك والتزامك؟ (سطرين بحد أقصى)',
      type: 'textarea',
      required: false,
      placeholder: 'اقنعنا في سطرين...',
    },
  ],
  'cv-designer': [
    {
      id: 'experience',
      text: 'كم سيرة ذاتية صممتها من قبل (تقريباً)؟',
      type: 'select',
      required: true,
      options: ['أقل من 10', '10-50', '50-100', 'أكثر من 100'],
    },
    {
      id: 'tools',
      text: 'ما الأدوات التي تستخدمها في تصميم السير الذاتية؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: Canva, Adobe InDesign, Figma, Word...',
    },
    {
      id: 'ats_knowledge',
      text: 'هل تعرف ما هو نظام ATS وكيف تصمم CV متوافق معه؟',
      type: 'radio',
      required: true,
      options: ['نعم، أعرفه وأصمم متوافق معه', 'سمعت عنه بس مش متعمق', 'لا أعرفه'],
    },
    {
      id: 'portfolio',
      text: 'مشاركة رابط لأعمالك السابقة (Portfolio)',
      type: 'url',
      required: false,
      placeholder: 'https://...',
    },
    {
      id: 'turnaround',
      text: 'كم يستغرق منك تصميم سيرة ذاتية واحدة؟',
      type: 'select',
      required: true,
      options: ['أقل من ساعة', '1-3 ساعات', '3-6 ساعات', 'يوم كامل'],
    },
  ],
  'graphic-designer': [
    {
      id: 'experience_years',
      text: 'كم سنة خبرة لديك في التصميم الجرافيكي؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-3 سنوات', '3-5 سنوات', 'أكثر من 5 سنوات'],
    },
    {
      id: 'tools',
      text: 'ما البرامج التي تتقن استخدامها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: Photoshop, Illustrator, Figma, Canva...',
    },
    {
      id: 'specialization',
      text: 'ما تخصصك الأساسي في التصميم؟',
      type: 'select',
      required: true,
      options: [
        'سوشيال ميديا',
        'هوية بصرية (Branding)',
        'UI/UX',
        'موشن جرافيك',
        'طباعة',
        'أكثر من تخصص',
      ],
    },
    {
      id: 'portfolio',
      text: 'رابط أعمالك السابقة (Behance, Dribbble, أو أي رابط)',
      type: 'url',
      required: true,
      placeholder: 'https://behance.net/...',
    },
    {
      id: 'creative_scenario',
      text: 'لو عميل طلب منك تصميم بوست سوشيال ميديا ومش عاجبه اللون، هتتعامل معاه إزاي؟',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح أسلوبك في التعامل مع feedback العملاء...',
    },
  ],
  tailor: [
    {
      id: 'experience',
      text: 'كم سنة خبرة لديك في الخياطة؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-3 سنوات', '3-5 سنوات', 'أكثر من 5 سنوات'],
    },
    {
      id: 'specialization',
      text: 'ما نوع الخياطة اللي بتشتغل فيها؟',
      type: 'select',
      required: true,
      options: ['ملابس رجالي', 'ملابس حريمي', 'ملابس أطفال', 'تعديلات', 'كل الأنواع'],
    },
    {
      id: 'machines',
      text: 'ما أنواع ماكينات الخياطة اللي بتشتغل عليها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: ماكينة أوفرلوك، ماكينة سنجر...',
    },
    {
      id: 'daily_capacity',
      text: 'كم قطعة ملابس تقدر تخلصها في اليوم؟',
      type: 'number',
      required: true,
      placeholder: 'العدد التقريبي',
    },
    {
      id: 'location',
      text: 'هل عندك ورشة خاصة ولا محتاج مكان؟',
      type: 'radio',
      required: true,
      options: ['عندي ورشة', 'بشتغل من البيت', 'محتاج مكان'],
    },
  ],
  'fabric-cutter': [
    {
      id: 'experience',
      text: 'كم سنة خبرة لديك في القص؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-3 سنوات', '3-5 سنوات', 'أكثر من 5 سنوات'],
    },
    {
      id: 'pattern_reading',
      text: 'هل تقدر تقرأ الباترونات (Patterns) وتنفذها؟',
      type: 'radio',
      required: true,
      options: ['نعم بامتياز', 'نعم بشكل أساسي', 'لا، بس عايز أتعلم'],
    },
    {
      id: 'fabrics',
      text: 'ما أنواع الأقمشة اللي عندك خبرة في قصها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: قطن، حرير، جينز، شيفون...',
    },
    {
      id: 'tools',
      text: 'ما الأدوات اللي بتستخدمها في القص؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: مقص كهربائي، كتر، طاولة قص...',
    },
    {
      id: 'precision',
      text: 'صف طريقتك في التأكد من دقة القص وتقليل الهدر في الأقمشة',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح أسلوبك...',
    },
  ],
  'affiliate-marketer': [
    {
      id: 'experience',
      text: 'هل عندك خبرة سابقة في التسويق بالعمولة؟',
      type: 'radio',
      required: true,
      options: ['نعم، أعمل في المجال', 'جربت قبل كده', 'لا، بس مهتم'],
    },
    {
      id: 'platforms',
      text: 'ما المنصات اللي هتستخدمها في التسويق؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: Facebook, Instagram, TikTok, YouTube...',
    },
    {
      id: 'audience',
      text: 'كم عدد متابعيك على السوشيال ميديا (تقريباً)؟',
      type: 'select',
      required: true,
      options: ['أقل من 1000', '1,000 - 5,000', '5,000 - 10,000', '10,000 - 50,000', 'أكثر من 50,000'],
    },
    {
      id: 'strategy',
      text: 'إيه استراتيجيتك لو طلبنا منك تسوق لخدمة كتابة السيرة الذاتية؟',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح خطتك التسويقية...',
    },
    {
      id: 'previous_results',
      text: 'لو اشتغلت affiliate قبل كده، إيه أحسن نتيجة حققتها؟',
      type: 'textarea',
      required: false,
      placeholder: 'مثال: حققت X مبيعة في شهر...',
    },
  ],
  developer: [
    {
      id: 'experience',
      text: 'كم سنة خبرة لديك في البرمجة؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-2 سنة', '2-4 سنوات', 'أكثر من 4 سنوات'],
    },
    {
      id: 'languages',
      text: 'ما لغات البرمجة والتقنيات اللي بتشتغل بيها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: JavaScript, React, Python, Node.js...',
    },
    {
      id: 'specialization',
      text: 'ما تخصصك الأساسي؟',
      type: 'select',
      required: true,
      options: ['Frontend', 'Backend', 'Full-Stack', 'Mobile', 'DevOps', 'أخرى'],
    },
    {
      id: 'github',
      text: 'رابط GitHub أو Portfolio',
      type: 'url',
      required: false,
      placeholder: 'https://github.com/...',
    },
    {
      id: 'project',
      text: 'احكيلنا عن أفضل مشروع برمجي عملته - إيه المشكلة اللي حلها وإيه التقنيات اللي استخدمتها؟',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح المشروع...',
    },
  ],
  'content-writer': [
    {
      id: 'experience',
      text: 'كم سنة خبرة لديك في كتابة المحتوى؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-2 سنة', '2-4 سنوات', 'أكثر من 4 سنوات'],
    },
    {
      id: 'content_types',
      text: 'ما أنواع المحتوى اللي بتكتبها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: بوستات سوشيال، مقالات، سكريبت فيديو، إعلانات...',
    },
    {
      id: 'language',
      text: 'ما اللغات اللي بتكتب بيها؟',
      type: 'select',
      required: true,
      options: ['عربي فقط', 'إنجليزي فقط', 'عربي وإنجليزي'],
    },
    {
      id: 'sample',
      text: 'اكتب لنا Caption قصير عن خدمة كتابة السيرة الذاتية بالذكاء الاصطناعي',
      type: 'textarea',
      required: true,
      placeholder: 'اكتب Caption إبداعي هنا...',
    },
    {
      id: 'portfolio',
      text: 'رابط لأعمالك السابقة (لو موجود)',
      type: 'url',
      required: false,
      placeholder: 'https://...',
    },
  ],
  'ugc-creator': [
    {
      id: 'tiktok_profile',
      text: 'رابط بروفايل TikTok الخاص بيك',
      type: 'url',
      required: false,
      placeholder: 'https://www.tiktok.com/@username',
    },
    {
      id: 'instagram_profile',
      text: 'رابط بروفايل Instagram الخاص بيك',
      type: 'url',
      required: false,
      placeholder: 'https://www.instagram.com/username',
    },
    {
      id: 'worked_before',
      text: 'هل اشتغلت UGC قبل كده؟',
      type: 'radio',
      required: true,
      options: ['نعم', 'لا'],
    },
    {
      id: 'video_price',
      text: 'كام سعر الفيديو الواحد؟ (بالجنيه المصري)',
      type: 'number',
      required: true,
      placeholder: 'مثال: 800',
    },
    {
      id: 'fixed_salary_monthly',
      text: 'لو هيكون مرتب ثابت، تتوقع كام في الشهر مقابل إنتاج من 1 إلى 5 فيديو يومياً؟',
      type: 'number',
      required: false,
      placeholder: 'اكتب المبلغ الشهري بالجنيه المصري',
    },
    {
      id: 'free_sample',
      text: 'هل تقدر تعملنا عينة مجانية؟',
      type: 'radio',
      required: false,
      options: ['نعم', 'لا', 'حسب نوع المنتج'],
    },
    {
      id: 'weekly_capacity',
      text: 'تقدر تسلّم كام فيديو في الأسبوع؟',
      type: 'select',
      required: false,
      options: ['1-3', '4-7', '8-12', '+12'],
    },
    {
      id: 'delivery_time',
      text: 'زمن التسليم المعتاد للفيديو الواحد؟',
      type: 'select',
      required: false,
      options: ['24 ساعة', '48 ساعة', '3-5 أيام', 'أكثر من 5 أيام'],
    },
    {
      id: 'cooperation_model',
      text: 'نوع التعاون المفضل؟',
      type: 'select',
      required: false,
      options: ['لكل فيديو', 'باقات شهرية', 'راتب ثابت', 'مرن حسب الاتفاق'],
    },
    {
      id: 'revision_policy',
      text: 'هل تقبل تعديلات بعد التسليم؟',
      type: 'select',
      required: false,
      options: ['تعديل واحد', 'تعديلين', '3 تعديلات أو أكثر', 'لا أقبل تعديلات'],
    },
    {
      id: 'video_quality',
      text: 'جودة التصوير المتاحة عندك؟',
      type: 'select',
      required: false,
      options: ['1080p', '2K', '4K', 'حسب المطلوب'],
    },
    {
      id: 'video_style',
      text: 'هل تقدر تعمل فيديوهات بأشكال مختلفة؟',
      type: 'select',
      required: false,
      options: ['Talking Head', 'Voice Over', 'Unboxing/Review', 'كل ما سبق'],
    },
    {
      id: 'language_dialect',
      text: 'اللغة أو اللهجة اللي تقدر تقدم بيها؟',
      type: 'select',
      required: false,
      options: ['عربي مصري', 'عربي فصحى', 'إنجليزي', 'عربي + إنجليزي'],
    },
    {
      id: 'start_availability',
      text: 'متاح تبدأ خلال قد إيه؟',
      type: 'select',
      required: false,
      options: ['فورًا', 'خلال 3 أيام', 'خلال أسبوع', 'أكثر من أسبوع'],
    },
    {
      id: 'content_niche',
      text: 'الأفضلية في مجال المحتوى؟',
      type: 'select',
      required: false,
      options: ['بيوتي/فاشن', 'Tech/Gadgets', 'خدمات رقمية', 'تعليم/تدريب', 'عام'],
    },
    {
      id: 'content_type',
      text: 'ما نوع المحتوى اللي بتعمله؟',
      type: 'select',
      required: true,
      options: ['فيديو Reels/TikTok', 'صور ومراجعات', 'Unboxing', 'كل الأنواع'],
    },
    {
      id: 'ideas',
      text: 'لو طلبنا منك تعمل Reel عن CVEEEZ، إيه الفكرة اللي هتعملها؟',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح فكرتك...',
    },
  ],
  'programming-intern': [
    {
      id: 'education',
      text: 'ما مرحلتك الدراسية الحالية؟',
      type: 'select',
      required: true,
      options: ['ثانوي', 'جامعة - سنة أولى/تانية', 'جامعة - سنة تالتة/رابعة', 'خريج', 'أخرى'],
    },
    {
      id: 'languages',
      text: 'ما لغات البرمجة اللي اتعلمتها (حتى لو مبتدئ)؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: HTML, CSS, JavaScript, Python...',
    },
    {
      id: 'interest',
      text: 'ما المجال اللي عايز تتعلمه أكتر؟',
      type: 'select',
      required: true,
      options: ['Frontend (React/Next.js)', 'Backend (Node.js/Python)', 'Mobile (React Native/Flutter)', 'مش متأكد لسه'],
    },
    {
      id: 'motivation',
      text: 'ليه عايز تتدرب معانا وإيه اللي تتوقعه من التدريب؟',
      type: 'textarea',
      required: true,
      placeholder: 'اكتب هنا...',
    },
    {
      id: 'availability',
      text: 'كم ساعة في الأسبوع تقدر تخصصها للتدريب؟',
      type: 'select',
      required: true,
      options: ['5-10 ساعات', '10-20 ساعة', '20-30 ساعة', '+30 ساعة (Full-time)'],
    },
  ],
  'cleaning-worker': [
    {
      id: 'experience',
      text: 'هل عندك خبرة سابقة في أعمال النظافة؟',
      type: 'radio',
      required: true,
      options: ['نعم، اشتغلت قبل كده', 'لا، بس مستعدة أتعلم'],
    },
    {
      id: 'availability',
      text: 'ما الأوقات المناسبة ليكي للعمل؟',
      type: 'select',
      required: true,
      options: ['صباحي (8ص - 2م)', 'مسائي (2م - 8م)', 'فترتين', 'مرن'],
    },
    {
      id: 'location',
      text: 'ما المنطقة اللي تقدري تشتغلي فيها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: مدينة نصر، المعادي، التجمع...',
    },
    {
      id: 'work_type',
      text: 'ما نوع العمل المفضل؟',
      type: 'select',
      required: true,
      options: ['منازل', 'مكاتب وشركات', 'كلاهما'],
    },
    {
      id: 'documents',
      text: 'هل عندك أوراق ثبوتية (بطاقة، شهادة صحية)؟',
      type: 'radio',
      required: true,
      options: ['نعم، كلها جاهزة', 'عندي بطاقة بس', 'محتاجة أجهزها'],
    },
  ],
};
