// src/lib/constants.ts
export const COMPANY = {
  name: 'CVEEEZ',
  nameAr: 'سي ڤييز',
  slogan: 'نحن نحقق أهدافك',
  sloganEn: 'We achieve your goals',
  description:
    'شركة متخصصة في خدمات كتابة السيرة الذاتية والتوظيف بالذكاء الاصطناعي',
  location: 'Cairo, Egypt',
  email: 'cveeez@cveeez.online',
  phones: [
    { number: '+201065236963', label: 'الخط الأول' },
    { number: '+201550363738', label: 'الخط الثاني' },
  ],
  supportPhone: { number: '0934678331', hours: 'من 10 صباحاً إلى 4 مساءً' },
  socials: {
    website: 'https://cveeez.net/',
    facebook: 'https://www.facebook.com/cveeez.eg',
    linkedin: 'https://www.linkedin.com/company/cveez/',
    instagram: 'https://www.instagram.com/cveeez0',
  },
  brandColor: '#22c55e',
  stats: {
    cvsCreated: '+10,000',
    happyUsers: '+10,000',
    templates: 21,
    satisfaction: '95%',
  },
} as const;

export const QR_LINKS = [
  { url: COMPANY.socials.website, label: 'الموقع الرسمي', icon: '🌐' },
  { url: COMPANY.socials.facebook, label: 'فيسبوك', icon: '📘' },
  { url: COMPANY.socials.linkedin, label: 'لينكدإن', icon: '💼' },
  { url: COMPANY.socials.instagram, label: 'إنستجرام', icon: '📸' },
  {
    url: `tel:${COMPANY.phones[0].number}`,
    label: COMPANY.phones[0].label,
    icon: '📞',
  },
  {
    url: `tel:${COMPANY.phones[1].number}`,
    label: COMPANY.phones[1].label,
    icon: '📱',
  },
  { url: `mailto:${COMPANY.email}`, label: 'البريد الإلكتروني', icon: '📧' },
] as const;

export const JOBS = [
  {
    id: 'moderator',
    title: 'مودريتور',
    titleEn: 'Moderator',
    icon: '🛡️',
    description: 'إدارة المحتوى والمجتمعات الرقمية',
    color: 'from-blue-500/20 to-blue-600/20',
  },
  {
    id: 'cv-designer',
    title: 'مصممي سيرة ذاتية',
    titleEn: 'CV Designer',
    icon: '📄',
    description: 'تصميم سير ذاتية احترافية',
    color: 'from-emerald-500/20 to-emerald-600/20',
  },
  {
    id: 'graphic-designer',
    title: 'مصمم عام',
    titleEn: 'Graphic Designer',
    icon: '🎨',
    description: 'تصميم جرافيك وبصريات إبداعية',
    color: 'from-purple-500/20 to-purple-600/20',
  },
  {
    id: 'tailor',
    title: 'خياطين',
    titleEn: 'Tailor',
    icon: '🧵',
    description: 'أعمال الخياطة والتفصيل',
    color: 'from-rose-500/20 to-rose-600/20',
  },
  {
    id: 'fabric-cutter',
    title: 'مقص دار',
    titleEn: 'Fabric Cutter',
    icon: '✂️',
    description: 'قص الأقمشة والباترونات',
    color: 'from-orange-500/20 to-orange-600/20',
  },
  {
    id: 'affiliate-marketer',
    title: 'مسوقين بالعمولة',
    titleEn: 'Affiliate Marketer',
    icon: '📢',
    description: 'تسويق بالعمولة وجلب عملاء',
    color: 'from-yellow-500/20 to-yellow-600/20',
  },
  {
    id: 'developer',
    title: 'مبرمجين',
    titleEn: 'Developer',
    icon: '💻',
    description: 'تطوير وبرمجة المواقع والتطبيقات',
    color: 'from-cyan-500/20 to-cyan-600/20',
  },
  {
    id: 'content-writer',
    title: 'كاتب محتوى',
    titleEn: 'Content Writer',
    icon: '✍️',
    description: 'كتابة محتوى إبداعي وتسويقي',
    color: 'from-indigo-500/20 to-indigo-600/20',
  },
  {
    id: 'ugc-creator',
    title: 'UGC',
    titleEn: 'UGC Creator',
    icon: '📱',
    description: 'صناعة محتوى المستخدمين',
    color: 'from-pink-500/20 to-pink-600/20',
  },
  {
    id: 'programming-intern',
    title: 'متدربين برمجة',
    titleEn: 'Programming Intern',
    icon: '🎓',
    description: 'تدريب وتعلم البرمجة',
    color: 'from-teal-500/20 to-teal-600/20',
  },
  {
    id: 'cleaning-worker',
    title: 'عاملة نظافة',
    titleEn: 'Cleaning Worker',
    icon: '🧹',
    description: 'خدمات النظافة والترتيب',
    color: 'from-lime-500/20 to-lime-600/20',
  },
] as const;

export type JobSlug = (typeof JOBS)[number]['id'];

// Job-specific questions
export const JOB_QUESTIONS: Record<
  string,
  Array<{
    id: string;
    text: string;
    type: 'text' | 'textarea' | 'select' | 'number' | 'url' | 'file' | 'radio';
    required: boolean;
    placeholder?: string;
    options?: string[];
  }>
> = {
  moderator: [
    {
      id: 'experience',
      text: 'كم سنة خبرة لديك في إدارة المحتوى أو المجتمعات الرقمية؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-2 سنة', '3-5 سنوات', 'أكثر من 5 سنوات'],
    },
    {
      id: 'platforms',
      text: 'ما المنصات التي لديك خبرة في إدارتها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: Facebook Groups, Discord, Telegram...',
    },
    {
      id: 'scenario',
      text: 'لو حد نشر محتوى مخالف في جروب بتديره، هتعمل إيه بالظبط؟',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح الخطوات اللي هتاخدها...',
    },
    {
      id: 'availability',
      text: 'كم ساعة يومياً يمكنك تخصيصها لهذا الدور؟',
      type: 'select',
      required: true,
      options: ['2-4 ساعات', '4-6 ساعات', '6-8 ساعات', 'Full-time'],
    },
    {
      id: 'tools',
      text: 'هل لديك خبرة في أي أدوات إدارة مجتمعات؟',
      type: 'text',
      required: false,
      placeholder: 'مثال: Hootsuite, Buffer, Meta Business Suite...',
    },
  ],
  'cv-designer': [
    {
      id: 'experience',
      text: 'كم سيرة ذاتية صممتها من قبل (تقريباً)؟',
      type: 'select',
      required: true,
      options: ['أقل من 10', '10-50', '50-100', 'أكثر من 100'],
    },
    {
      id: 'tools',
      text: 'ما الأدوات التي تستخدمها في تصميم السير الذاتية؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: Canva, Adobe InDesign, Figma, Word...',
    },
    {
      id: 'ats_knowledge',
      text: 'هل تعرف ما هو نظام ATS وكيف تصمم CV متوافق معه؟',
      type: 'radio',
      required: true,
      options: ['نعم، أعرفه وأصمم متوافق معه', 'سمعت عنه بس مش متعمق', 'لا أعرفه'],
    },
    {
      id: 'portfolio',
      text: 'مشاركة رابط لأعمالك السابقة (Portfolio)',
      type: 'url',
      required: false,
      placeholder: 'https://...',
    },
    {
      id: 'turnaround',
      text: 'كم يستغرق منك تصميم سيرة ذاتية واحدة؟',
      type: 'select',
      required: true,
      options: ['أقل من ساعة', '1-3 ساعات', '3-6 ساعات', 'يوم كامل'],
    },
  ],
  'graphic-designer': [
    {
      id: 'experience_years',
      text: 'كم سنة خبرة لديك في التصميم الجرافيكي؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-3 سنوات', '3-5 سنوات', 'أكثر من 5 سنوات'],
    },
    {
      id: 'tools',
      text: 'ما البرامج التي تتقن استخدامها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: Photoshop, Illustrator, Figma, Canva...',
    },
    {
      id: 'specialization',
      text: 'ما تخصصك الأساسي في التصميم؟',
      type: 'select',
      required: true,
      options: [
        'سوشيال ميديا',
        'هوية بصرية (Branding)',
        'UI/UX',
        'موشن جرافيك',
        'طباعة',
        'أكثر من تخصص',
      ],
    },
    {
      id: 'portfolio',
      text: 'رابط أعمالك السابقة (Behance, Dribbble, أو أي رابط)',
      type: 'url',
      required: true,
      placeholder: 'https://behance.net/...',
    },
    {
      id: 'creative_scenario',
      text: 'لو عميل طلب منك تصميم بوست سوشيال ميديا ومش عاجبه اللون، هتتعامل معاه إزاي؟',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح أسلوبك في التعامل مع feedback العملاء...',
    },
  ],
  tailor: [
    {
      id: 'experience',
      text: 'كم سنة خبرة لديك في الخياطة؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-3 سنوات', '3-5 سنوات', 'أكثر من 5 سنوات'],
    },
    {
      id: 'specialization',
      text: 'ما نوع الخياطة اللي بتشتغل فيها؟',
      type: 'select',
      required: true,
      options: ['ملابس رجالي', 'ملابس حريمي', 'ملابس أطفال', 'تعديلات', 'كل الأنواع'],
    },
    {
      id: 'machines',
      text: 'ما أنواع ماكينات الخياطة اللي بتشتغل عليها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: ماكينة أوفرلوك، ماكينة سنجر...',
    },
    {
      id: 'daily_capacity',
      text: 'كم قطعة ملابس تقدر تخلصها في اليوم؟',
      type: 'number',
      required: true,
      placeholder: 'العدد التقريبي',
    },
    {
      id: 'location',
      text: 'هل عندك ورشة خاصة ولا محتاج مكان؟',
      type: 'radio',
      required: true,
      options: ['عندي ورشة', 'بشتغل من البيت', 'محتاج مكان'],
    },
  ],
  'fabric-cutter': [
    {
      id: 'experience',
      text: 'كم سنة خبرة لديك في القص؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-3 سنوات', '3-5 سنوات', 'أكثر من 5 سنوات'],
    },
    {
      id: 'pattern_reading',
      text: 'هل تقدر تقرأ الباترونات (Patterns) وتنفذها؟',
      type: 'radio',
      required: true,
      options: ['نعم بامتياز', 'نعم بشكل أساسي', 'لا، بس عايز أتعلم'],
    },
    {
      id: 'fabrics',
      text: 'ما أنواع الأقمشة اللي عندك خبرة في قصها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: قطن، حرير، جينز، شيفون...',
    },
    {
      id: 'tools',
      text: 'ما الأدوات اللي بتستخدمها في القص؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: مقص كهربائي، كتر، طاولة قص...',
    },
    {
      id: 'precision',
      text: 'صف طريقتك في التأكد من دقة القص وتقليل الهدر في الأقمشة',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح أسلوبك...',
    },
  ],
  'affiliate-marketer': [
    {
      id: 'experience',
      text: 'هل عندك خبرة سابقة في التسويق بالعمولة؟',
      type: 'radio',
      required: true,
      options: ['نعم، أعمل في المجال', 'جربت قبل كده', 'لا، بس مهتم'],
    },
    {
      id: 'platforms',
      text: 'ما المنصات اللي هتستخدمها في التسويق؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: Facebook, Instagram, TikTok, YouTube...',
    },
    {
      id: 'audience',
      text: 'كم عدد متابعيك على السوشيال ميديا (تقريباً)؟',
      type: 'select',
      required: true,
      options: ['أقل من 1000', '1,000 - 5,000', '5,000 - 10,000', '10,000 - 50,000', 'أكثر من 50,000'],
    },
    {
      id: 'strategy',
      text: 'إيه استراتيجيتك لو طلبنا منك تسوق لخدمة كتابة السيرة الذاتية؟',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح خطتك التسويقية...',
    },
    {
      id: 'previous_results',
      text: 'لو اشتغلت affiliate قبل كده، إيه أحسن نتيجة حققتها؟',
      type: 'textarea',
      required: false,
      placeholder: 'مثال: حققت X مبيعة في شهر...',
    },
  ],
  developer: [
    {
      id: 'experience',
      text: 'كم سنة خبرة لديك في البرمجة؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-2 سنة', '2-4 سنوات', 'أكثر من 4 سنوات'],
    },
    {
      id: 'languages',
      text: 'ما لغات البرمجة والتقنيات اللي بتشتغل بيها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: JavaScript, React, Python, Node.js...',
    },
    {
      id: 'specialization',
      text: 'ما تخصصك الأساسي؟',
      type: 'select',
      required: true,
      options: ['Frontend', 'Backend', 'Full-Stack', 'Mobile', 'DevOps', 'أخرى'],
    },
    {
      id: 'github',
      text: 'رابط GitHub أو Portfolio',
      type: 'url',
      required: false,
      placeholder: 'https://github.com/...',
    },
    {
      id: 'project',
      text: 'احكيلنا عن أفضل مشروع برمجي عملته - إيه المشكلة اللي حلها وإيه التقنيات اللي استخدمتها؟',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح المشروع...',
    },
  ],
  'content-writer': [
    {
      id: 'experience',
      text: 'كم سنة خبرة لديك في كتابة المحتوى؟',
      type: 'select',
      required: true,
      options: ['أقل من سنة', '1-2 سنة', '2-4 سنوات', 'أكثر من 4 سنوات'],
    },
    {
      id: 'content_types',
      text: 'ما أنواع المحتوى اللي بتكتبها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: بوستات سوشيال، مقالات، سكريبت فيديو، إعلانات...',
    },
    {
      id: 'language',
      text: 'ما اللغات اللي بتكتب بيها؟',
      type: 'select',
      required: true,
      options: ['عربي فقط', 'إنجليزي فقط', 'عربي وإنجليزي'],
    },
    {
      id: 'sample',
      text: 'اكتب لنا Caption قصير عن خدمة كتابة السيرة الذاتية بالذكاء الاصطناعي',
      type: 'textarea',
      required: true,
      placeholder: 'اكتب Caption إبداعي هنا...',
    },
    {
      id: 'portfolio',
      text: 'رابط لأعمالك السابقة (لو موجود)',
      type: 'url',
      required: false,
      placeholder: 'https://...',
    },
  ],
  'ugc-creator': [
    {
      id: 'experience',
      text: 'هل عندك خبرة سابقة في صناعة UGC؟',
      type: 'radio',
      required: true,
      options: ['نعم، بشتغل في المجال', 'جربت قبل كده', 'لا، بس مهتم وعايز أبدأ'],
    },
    {
      id: 'content_type',
      text: 'ما نوع المحتوى اللي بتعمله؟',
      type: 'select',
      required: true,
      options: ['فيديو Reels/TikTok', 'صور ومراجعات', 'Unboxing', 'كل الأنواع'],
    },
    {
      id: 'equipment',
      text: 'ما المعدات اللي عندك لتصوير المحتوى؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: iPhone 15, Ring Light, Microphone...',
    },
    {
      id: 'social_links',
      text: 'رابط حسابك على TikTok أو Instagram',
      type: 'url',
      required: false,
      placeholder: 'https://tiktok.com/@...',
    },
    {
      id: 'ideas',
      text: 'لو طلبنا منك تعمل Reel عن CVEEEZ، إيه الفكرة اللي هتعملها؟',
      type: 'textarea',
      required: true,
      placeholder: 'اشرح فكرتك...',
    },
  ],
  'programming-intern': [
    {
      id: 'education',
      text: 'ما مرحلتك الدراسية الحالية؟',
      type: 'select',
      required: true,
      options: ['ثانوي', 'جامعة - سنة أولى/تانية', 'جامعة - سنة تالتة/رابعة', 'خريج', 'أخرى'],
    },
    {
      id: 'languages',
      text: 'ما لغات البرمجة اللي اتعلمتها (حتى لو مبتدئ)؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: HTML, CSS, JavaScript, Python...',
    },
    {
      id: 'interest',
      text: 'ما المجال اللي عايز تتعلمه أكتر؟',
      type: 'select',
      required: true,
      options: ['Frontend (React/Next.js)', 'Backend (Node.js/Python)', 'Mobile (React Native/Flutter)', 'مش متأكد لسه'],
    },
    {
      id: 'motivation',
      text: 'ليه عايز تتدرب معانا وإيه اللي تتوقعه من التدريب؟',
      type: 'textarea',
      required: true,
      placeholder: 'اكتب هنا...',
    },
    {
      id: 'availability',
      text: 'كم ساعة في الأسبوع تقدر تخصصها للتدريب؟',
      type: 'select',
      required: true,
      options: ['5-10 ساعات', '10-20 ساعة', '20-30 ساعة', '+30 ساعة (Full-time)'],
    },
  ],
  'cleaning-worker': [
    {
      id: 'experience',
      text: 'هل عندك خبرة سابقة في أعمال النظافة؟',
      type: 'radio',
      required: true,
      options: ['نعم، اشتغلت قبل كده', 'لا، بس مستعدة أتعلم'],
    },
    {
      id: 'availability',
      text: 'ما الأوقات المناسبة ليكي للعمل؟',
      type: 'select',
      required: true,
      options: ['صباحي (8ص - 2م)', 'مسائي (2م - 8م)', 'فترتين', 'مرن'],
    },
    {
      id: 'location',
      text: 'ما المنطقة اللي تقدري تشتغلي فيها؟',
      type: 'text',
      required: true,
      placeholder: 'مثال: مدينة نصر، المعادي، التجمع...',
    },
    {
      id: 'work_type',
      text: 'ما نوع العمل المفضل؟',
      type: 'select',
      required: true,
      options: ['منازل', 'مكاتب وشركات', 'كلاهما'],
    },
    {
      id: 'documents',
      text: 'هل عندك أوراق ثبوتية (بطاقة، شهادة صحية)؟',
      type: 'radio',
      required: true,
      options: ['نعم، كلها جاهزة', 'عندي بطاقة بس', 'محتاجة أجهزها'],
    },
  ],
};
